import Footer from "@/app/(user)/components/Footer";
import "../globals.css";
import Navbar from "@/app/(user)/components/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <main className="pt-24 md:pt-0">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
